<?php
/**
 * WebhookConditionalParams
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.4
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Adobe\ESign\Model;

use \ArrayAccess;
use \Adobe\ESign\ObjectSerializer;

/**
 * WebhookConditionalParams Class Doc Comment
 *
 * @category Class
 * @package  Adobe\ESign
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WebhookConditionalParams implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WebhookConditionalParams';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'webhookWidgetEvents' => '\Adobe\ESign\Model\WebhookWidgetEvents',
        'webhookMegaSignEvents' => '\Adobe\ESign\Model\WebhookMegaSignEvents',
        'webhookLibraryDocumentEvents' => '\Adobe\ESign\Model\WebhookLibraryDocumentEvents',
        'webhookAgreementEvents' => '\Adobe\ESign\Model\WebhookAgreementEvents'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'webhookWidgetEvents' => null,
        'webhookMegaSignEvents' => null,
        'webhookLibraryDocumentEvents' => null,
        'webhookAgreementEvents' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'webhookWidgetEvents' => 'webhookWidgetEvents',
        'webhookMegaSignEvents' => 'webhookMegaSignEvents',
        'webhookLibraryDocumentEvents' => 'webhookLibraryDocumentEvents',
        'webhookAgreementEvents' => 'webhookAgreementEvents'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'webhookWidgetEvents' => 'setWebhookWidgetEvents',
        'webhookMegaSignEvents' => 'setWebhookMegaSignEvents',
        'webhookLibraryDocumentEvents' => 'setWebhookLibraryDocumentEvents',
        'webhookAgreementEvents' => 'setWebhookAgreementEvents'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'webhookWidgetEvents' => 'getWebhookWidgetEvents',
        'webhookMegaSignEvents' => 'getWebhookMegaSignEvents',
        'webhookLibraryDocumentEvents' => 'getWebhookLibraryDocumentEvents',
        'webhookAgreementEvents' => 'getWebhookAgreementEvents'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['webhookWidgetEvents'] = isset($data['webhookWidgetEvents']) ? $data['webhookWidgetEvents'] : null;
        $this->container['webhookMegaSignEvents'] = isset($data['webhookMegaSignEvents']) ? $data['webhookMegaSignEvents'] : null;
        $this->container['webhookLibraryDocumentEvents'] = isset($data['webhookLibraryDocumentEvents']) ? $data['webhookLibraryDocumentEvents'] : null;
        $this->container['webhookAgreementEvents'] = isset($data['webhookAgreementEvents']) ? $data['webhookAgreementEvents'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets webhookWidgetEvents
     *
     * @return \Adobe\ESign\Model\WebhookWidgetEvents
     */
    public function getWebhookWidgetEvents()
    {
        return $this->container['webhookWidgetEvents'];
    }

    /**
     * Sets webhookWidgetEvents
     *
     * @param \Adobe\ESign\Model\WebhookWidgetEvents $webhookWidgetEvents Conditional parameters for webhook widget events
     *
     * @return $this
     */
    public function setWebhookWidgetEvents($webhookWidgetEvents)
    {
        $this->container['webhookWidgetEvents'] = $webhookWidgetEvents;

        return $this;
    }

    /**
     * Gets webhookMegaSignEvents
     *
     * @return \Adobe\ESign\Model\WebhookMegaSignEvents
     */
    public function getWebhookMegaSignEvents()
    {
        return $this->container['webhookMegaSignEvents'];
    }

    /**
     * Sets webhookMegaSignEvents
     *
     * @param \Adobe\ESign\Model\WebhookMegaSignEvents $webhookMegaSignEvents Conditional parameters for webhook megasign events
     *
     * @return $this
     */
    public function setWebhookMegaSignEvents($webhookMegaSignEvents)
    {
        $this->container['webhookMegaSignEvents'] = $webhookMegaSignEvents;

        return $this;
    }

    /**
     * Gets webhookLibraryDocumentEvents
     *
     * @return \Adobe\ESign\Model\WebhookLibraryDocumentEvents
     */
    public function getWebhookLibraryDocumentEvents()
    {
        return $this->container['webhookLibraryDocumentEvents'];
    }

    /**
     * Sets webhookLibraryDocumentEvents
     *
     * @param \Adobe\ESign\Model\WebhookLibraryDocumentEvents $webhookLibraryDocumentEvents Conditional parameters for webhook library document events
     *
     * @return $this
     */
    public function setWebhookLibraryDocumentEvents($webhookLibraryDocumentEvents)
    {
        $this->container['webhookLibraryDocumentEvents'] = $webhookLibraryDocumentEvents;

        return $this;
    }

    /**
     * Gets webhookAgreementEvents
     *
     * @return \Adobe\ESign\Model\WebhookAgreementEvents
     */
    public function getWebhookAgreementEvents()
    {
        return $this->container['webhookAgreementEvents'];
    }

    /**
     * Sets webhookAgreementEvents
     *
     * @param \Adobe\ESign\Model\WebhookAgreementEvents $webhookAgreementEvents Conditional parameters for webhook agreement events
     *
     * @return $this
     */
    public function setWebhookAgreementEvents($webhookAgreementEvents)
    {
        $this->container['webhookAgreementEvents'] = $webhookAgreementEvents;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


