<?php
/**
 * WidgetMembersInfo
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.4
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Adobe\ESign\Model;

use \ArrayAccess;
use \Adobe\ESign\ObjectSerializer;

/**
 * WidgetMembersInfo Class Doc Comment
 *
 * @category Class
 * @package  Adobe\ESign
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WidgetMembersInfo implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WidgetMembersInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ccsInfo' => '\Adobe\ESign\Model\CCParticipantInfo[]',
        'additionalParticipantSets' => '\Adobe\ESign\Model\DetailedWidgetParticipantSetInfo[]',
        'widgetParticipantSet' => '\Adobe\ESign\Model\DetailedWidgetParticipantSetInfo',
        'sharesInfo' => '\Adobe\ESign\Model\ShareParticipantInfo[]',
        'creatorInfo' => '\Adobe\ESign\Model\SenderInfo'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ccsInfo' => null,
        'additionalParticipantSets' => null,
        'widgetParticipantSet' => null,
        'sharesInfo' => null,
        'creatorInfo' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ccsInfo' => 'ccsInfo',
        'additionalParticipantSets' => 'additionalParticipantSets',
        'widgetParticipantSet' => 'widgetParticipantSet',
        'sharesInfo' => 'sharesInfo',
        'creatorInfo' => 'creatorInfo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ccsInfo' => 'setCcsInfo',
        'additionalParticipantSets' => 'setAdditionalParticipantSets',
        'widgetParticipantSet' => 'setWidgetParticipantSet',
        'sharesInfo' => 'setSharesInfo',
        'creatorInfo' => 'setCreatorInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ccsInfo' => 'getCcsInfo',
        'additionalParticipantSets' => 'getAdditionalParticipantSets',
        'widgetParticipantSet' => 'getWidgetParticipantSet',
        'sharesInfo' => 'getSharesInfo',
        'creatorInfo' => 'getCreatorInfo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ccsInfo'] = isset($data['ccsInfo']) ? $data['ccsInfo'] : null;
        $this->container['additionalParticipantSets'] = isset($data['additionalParticipantSets']) ? $data['additionalParticipantSets'] : null;
        $this->container['widgetParticipantSet'] = isset($data['widgetParticipantSet']) ? $data['widgetParticipantSet'] : null;
        $this->container['sharesInfo'] = isset($data['sharesInfo']) ? $data['sharesInfo'] : null;
        $this->container['creatorInfo'] = isset($data['creatorInfo']) ? $data['creatorInfo'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ccsInfo
     *
     * @return \Adobe\ESign\Model\CCParticipantInfo[]
     */
    public function getCcsInfo()
    {
        return $this->container['ccsInfo'];
    }

    /**
     * Sets ccsInfo
     *
     * @param \Adobe\ESign\Model\CCParticipantInfo[] $ccsInfo Information of CC participants of the widget.
     *
     * @return $this
     */
    public function setCcsInfo($ccsInfo)
    {
        $this->container['ccsInfo'] = $ccsInfo;

        return $this;
    }

    /**
     * Gets additionalParticipantSets
     *
     * @return \Adobe\ESign\Model\DetailedWidgetParticipantSetInfo[]
     */
    public function getAdditionalParticipantSets()
    {
        return $this->container['additionalParticipantSets'];
    }

    /**
     * Sets additionalParticipantSets
     *
     * @param \Adobe\ESign\Model\DetailedWidgetParticipantSetInfo[] $additionalParticipantSets Information about the widget additional participant Sets
     *
     * @return $this
     */
    public function setAdditionalParticipantSets($additionalParticipantSets)
    {
        $this->container['additionalParticipantSets'] = $additionalParticipantSets;

        return $this;
    }

    /**
     * Gets widgetParticipantSet
     *
     * @return \Adobe\ESign\Model\DetailedWidgetParticipantSetInfo
     */
    public function getWidgetParticipantSet()
    {
        return $this->container['widgetParticipantSet'];
    }

    /**
     * Sets widgetParticipantSet
     *
     * @param \Adobe\ESign\Model\DetailedWidgetParticipantSetInfo $widgetParticipantSet Information about the widget participant Set
     *
     * @return $this
     */
    public function setWidgetParticipantSet($widgetParticipantSet)
    {
        $this->container['widgetParticipantSet'] = $widgetParticipantSet;

        return $this;
    }

    /**
     * Gets sharesInfo
     *
     * @return \Adobe\ESign\Model\ShareParticipantInfo[]
     */
    public function getSharesInfo()
    {
        return $this->container['sharesInfo'];
    }

    /**
     * Sets sharesInfo
     *
     * @param \Adobe\ESign\Model\ShareParticipantInfo[] $sharesInfo Information of the participants with whom the widget has been shared.
     *
     * @return $this
     */
    public function setSharesInfo($sharesInfo)
    {
        $this->container['sharesInfo'] = $sharesInfo;

        return $this;
    }

    /**
     * Gets creatorInfo
     *
     * @return \Adobe\ESign\Model\SenderInfo
     */
    public function getCreatorInfo()
    {
        return $this->container['creatorInfo'];
    }

    /**
     * Sets creatorInfo
     *
     * @param \Adobe\ESign\Model\SenderInfo $creatorInfo Information of the creator of the widget.
     *
     * @return $this
     */
    public function setCreatorInfo($creatorInfo)
    {
        $this->container['creatorInfo'] = $creatorInfo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


