<?php
/**
 * AgreementCreationInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.4
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Adobe\ESign;

/**
 * AgreementCreationInfoTest Class Doc Comment
 *
 * @category    Class
 * @description AgreementCreationInfo
 * @package     Adobe\ESign
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AgreementCreationInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AgreementCreationInfo"
     */
    public function testAgreementCreationInfo()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "vaultingInfo"
     */
    public function testPropertyVaultingInfo()
    {
    }

    /**
     * Test attribute "securityOption"
     */
    public function testPropertySecurityOption()
    {
    }

    /**
     * Test attribute "postSignOption"
     */
    public function testPropertyPostSignOption()
    {
    }

    /**
     * Test attribute "ccs"
     */
    public function testPropertyCcs()
    {
    }

    /**
     * Test attribute "documentVisibilityEnabled"
     */
    public function testPropertyDocumentVisibilityEnabled()
    {
    }

    /**
     * Test attribute "senderEmail"
     */
    public function testPropertySenderEmail()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "mergeFieldInfo"
     */
    public function testPropertyMergeFieldInfo()
    {
    }

    /**
     * Test attribute "firstReminderDelay"
     */
    public function testPropertyFirstReminderDelay()
    {
    }

    /**
     * Test attribute "emailOption"
     */
    public function testPropertyEmailOption()
    {
    }

    /**
     * Test attribute "signatureType"
     */
    public function testPropertySignatureType()
    {
    }

    /**
     * Test attribute "externalId"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "deviceInfo"
     */
    public function testPropertyDeviceInfo()
    {
    }

    /**
     * Test attribute "reminderFrequency"
     */
    public function testPropertyReminderFrequency()
    {
    }

    /**
     * Test attribute "createdDate"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "participantSetsInfo"
     */
    public function testPropertyParticipantSetsInfo()
    {
    }

    /**
     * Test attribute "expirationTime"
     */
    public function testPropertyExpirationTime()
    {
    }

    /**
     * Test attribute "formFieldLayerTemplates"
     */
    public function testPropertyFormFieldLayerTemplates()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "fileInfos"
     */
    public function testPropertyFileInfos()
    {
    }

    /**
     * Test attribute "workflowId"
     */
    public function testPropertyWorkflowId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
