<?php
/**
 * FormFieldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.4
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Adobe\ESign;

/**
 * FormFieldTest Class Doc Comment
 *
 * @category    Class
 * @description A form field for an agreement.
 * @package     Adobe\ESign
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormFieldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FormField"
     */
    public function testFormField()
    {
    }

    /**
     * Test attribute "radioCheckType"
     */
    public function testPropertyRadioCheckType()
    {
    }

    /**
     * Test attribute "borderColor"
     */
    public function testPropertyBorderColor()
    {
    }

    /**
     * Test attribute "valueExpression"
     */
    public function testPropertyValueExpression()
    {
    }

    /**
     * Test attribute "maskingText"
     */
    public function testPropertyMaskingText()
    {
    }

    /**
     * Test attribute "defaultValue"
     */
    public function testPropertyDefaultValue()
    {
    }

    /**
     * Test attribute "masked"
     */
    public function testPropertyMasked()
    {
    }

    /**
     * Test attribute "minLength"
     */
    public function testPropertyMinLength()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "tooltip"
     */
    public function testPropertyTooltip()
    {
    }

    /**
     * Test attribute "hiddenOptions"
     */
    public function testPropertyHiddenOptions()
    {
    }

    /**
     * Test attribute "required"
     */
    public function testPropertyRequired()
    {
    }

    /**
     * Test attribute "validationData"
     */
    public function testPropertyValidationData()
    {
    }

    /**
     * Test attribute "minValue"
     */
    public function testPropertyMinValue()
    {
    }

    /**
     * Test attribute "borderWidth"
     */
    public function testPropertyBorderWidth()
    {
    }

    /**
     * Test attribute "urlOverridable"
     */
    public function testPropertyUrlOverridable()
    {
    }

    /**
     * Test attribute "inputType"
     */
    public function testPropertyInputType()
    {
    }

    /**
     * Test attribute "borderStyle"
     */
    public function testPropertyBorderStyle()
    {
    }

    /**
     * Test attribute "calculated"
     */
    public function testPropertyCalculated()
    {
    }

    /**
     * Test attribute "contentType"
     */
    public function testPropertyContentType()
    {
    }

    /**
     * Test attribute "validation"
     */
    public function testPropertyValidation()
    {
    }

    /**
     * Test attribute "displayLabel"
     */
    public function testPropertyDisplayLabel()
    {
    }

    /**
     * Test attribute "hyperlink"
     */
    public function testPropertyHyperlink()
    {
    }

    /**
     * Test attribute "backgroundColor"
     */
    public function testPropertyBackgroundColor()
    {
    }

    /**
     * Test attribute "visible"
     */
    public function testPropertyVisible()
    {
    }

    /**
     * Test attribute "displayFormatType"
     */
    public function testPropertyDisplayFormatType()
    {
    }

    /**
     * Test attribute "maxValue"
     */
    public function testPropertyMaxValue()
    {
    }

    /**
     * Test attribute "validationErrMsg"
     */
    public function testPropertyValidationErrMsg()
    {
    }

    /**
     * Test attribute "displayFormat"
     */
    public function testPropertyDisplayFormat()
    {
    }

    /**
     * Test attribute "visibleOptions"
     */
    public function testPropertyVisibleOptions()
    {
    }

    /**
     * Test attribute "readOnly"
     */
    public function testPropertyReadOnly()
    {
    }

    /**
     * Test attribute "fontName"
     */
    public function testPropertyFontName()
    {
    }

    /**
     * Test attribute "conditionalAction"
     */
    public function testPropertyConditionalAction()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "fontSize"
     */
    public function testPropertyFontSize()
    {
    }

    /**
     * Test attribute "locations"
     */
    public function testPropertyLocations()
    {
    }

    /**
     * Test attribute "assignee"
     */
    public function testPropertyAssignee()
    {
    }

    /**
     * Test attribute "alignment"
     */
    public function testPropertyAlignment()
    {
    }

    /**
     * Test attribute "fontColor"
     */
    public function testPropertyFontColor()
    {
    }

    /**
     * Test attribute "maxLength"
     */
    public function testPropertyMaxLength()
    {
    }
}
