<?php
/**
 * WidgetInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.4
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Adobe\ESign;

/**
 * WidgetInfoTest Class Doc Comment
 *
 * @category    Class
 * @description WidgetInfo
 * @package     Adobe\ESign
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WidgetInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WidgetInfo"
     */
    public function testWidgetInfo()
    {
    }

    /**
     * Test attribute "additionalParticipantSetsInfo"
     */
    public function testPropertyAdditionalParticipantSetsInfo()
    {
    }

    /**
     * Test attribute "creatorEmail"
     */
    public function testPropertyCreatorEmail()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "vaultingInfo"
     */
    public function testPropertyVaultingInfo()
    {
    }

    /**
     * Test attribute "securityOption"
     */
    public function testPropertySecurityOption()
    {
    }

    /**
     * Test attribute "widgetParticipantSetInfo"
     */
    public function testPropertyWidgetParticipantSetInfo()
    {
    }

    /**
     * Test attribute "ccs"
     */
    public function testPropertyCcs()
    {
    }

    /**
     * Test attribute "createdDate"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "completionInfo"
     */
    public function testPropertyCompletionInfo()
    {
    }

    /**
     * Test attribute "authFailureInfo"
     */
    public function testPropertyAuthFailureInfo()
    {
    }

    /**
     * Test attribute "fileInfos"
     */
    public function testPropertyFileInfos()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
