<?php
/**
 * WidgetEventTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adobe\ESign
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.4
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Adobe\ESign;

/**
 * WidgetEventTest Class Doc Comment
 *
 * @category    Class
 * @description WidgetEvent
 * @package     Adobe\ESign
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WidgetEventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WidgetEvent"
     */
    public function testWidgetEvent()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "initiatingUserName"
     */
    public function testPropertyInitiatingUserName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "actingUserName"
     */
    public function testPropertyActingUserName()
    {
    }

    /**
     * Test attribute "actingUserIpAddress"
     */
    public function testPropertyActingUserIpAddress()
    {
    }

    /**
     * Test attribute "participantEmail"
     */
    public function testPropertyParticipantEmail()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "participantRole"
     */
    public function testPropertyParticipantRole()
    {
    }

    /**
     * Test attribute "vaultEventId"
     */
    public function testPropertyVaultEventId()
    {
    }

    /**
     * Test attribute "participantId"
     */
    public function testPropertyParticipantId()
    {
    }

    /**
     * Test attribute "versionId"
     */
    public function testPropertyVersionId()
    {
    }

    /**
     * Test attribute "actingUserEmail"
     */
    public function testPropertyActingUserEmail()
    {
    }

    /**
     * Test attribute "devicePhoneNumber"
     */
    public function testPropertyDevicePhoneNumber()
    {
    }

    /**
     * Test attribute "initiatingUserEmail"
     */
    public function testPropertyInitiatingUserEmail()
    {
    }

    /**
     * Test attribute "digitalSignatureInfo"
     */
    public function testPropertyDigitalSignatureInfo()
    {
    }

    /**
     * Test attribute "vaultProviderName"
     */
    public function testPropertyVaultProviderName()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "synchronizationId"
     */
    public function testPropertySynchronizationId()
    {
    }

    /**
     * Test attribute "deviceLocation"
     */
    public function testPropertyDeviceLocation()
    {
    }
}
